table:
  name: patient_field_config
  schema: public
insert_permissions:
  - role: clinic_user
    permission:
      check:
        _and:
          - clinic_id:
              _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
      columns:
        - clinic_id
        - field_key
        - field_label
        - display_order
        - is_displayed
        - is_required
        - is_active
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - id
        - clinic_id
        - field_key
        - field_label
        - display_order
        - is_displayed
        - is_required
        - is_active
        - created_at
        - created_by
        - updated_at
        - updated_by
      filter:
        clinic_id:
          _eq: X-Hasura-Clinic-Id
update_permissions:
  - role: clinic_user
    permission:
      columns:
        - field_label
        - display_order
        - is_displayed
        - is_required
        - is_active
      filter:
        clinic_id:
          _eq: X-Hasura-Clinic-Id
      check:
        _and:
          - clinic_id:
              _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
delete_permissions:
  - role: clinic_user
    permission:
      filter:
        _and:
          - clinic_id:
              _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
